name: Edit badges

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        description: the repo to edit badges in
        required: true
      repo_branch:
        type: string
        description: the branch to edit badges for
        required: true
      vers:
        type: string
        description: the version value to edit badges with
        required: true

permissions:
  contents: write

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updater repository
        uses: actions/checkout@v4
        with:
          repository: mm808/update_readme_badges
          ref: main
          path: update_readme_badges

      - name: setup env inputs
        shell: bash
        run: |
          # cd update_readme_badges
          set -eu

          echo pwd
          echo ls -al

          echo "The repo ${{ inputs.repo_name }}"
          echo "The branch ${{ inputs.repo_branch }}"
          echo "The vers ${{ inputs.vers }}"
          if [[ "${{ inputs.repo_branch }}" == "main" ]]; then
            env="PROD"
          else
            env=$(echo "${{ inputs.repo_branch }}" | tr '[:lower:]' '[:upper:]')
          fi
          echo "The env ${env}"

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_name }}
          ref: docs
          path: ${{ inputs.repo_name }}

      - name: edit vers svg
        shell: bash
        run: |
          set -eu
          cd ${{ inputs.repo_name }}/docs
          # Replace the VER-xxx.xxx with the input version
          sed -i '' "s/\(<h3>"${env}"<\/h3>.*VER-\)[0-9]\+\.[0-9]\+\(-blue?style=for-the-badge<\/img>\)/\1${{ inputs.vers }}\2/" index.html

      - name: Configure git and push commit
        run: |
          set -eu
          cd ${{ inputs.repo_name }}
          git config user.name "mm808"
          git config user.email "mm808@users.noreply.github.com"
          git add .
          git commit -m "Automated badge update by update_readme_badges GitHub workflow"
          git push
