name: Edit badges

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        required: true
      repo_branch:
        type: string
        required: true
      env_name:
        type: string
        required: true
      vers:
        type: string
        required: true
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        env:
          ${{secrets.GITHUB_TOKEN}}

      - name: debug inputs
        run: |
          echo "The repo ${{ inputs.repo_name }}"
          echo "The branch ${{ inputs.repo_branch }}"
          echo "The vers ${{ inputs.vers }}"
          echo "The env_name ${{ inputs.env_name }}"

      # - name: edit vers svg