name: Edit badges

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        description: the repo to edit badges in
        required: true
      repo_branch:
        type: string
        description: the branch to edit badges for
        required: true
      vers:
        type: string
        description: the version value to edit badges with
        required: true

permissions:
  contents: write

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: setup env inputs
        shell: bash
        run: |
          echo "The repo ${{ inputs.repo_name }}"
          echo "The branch ${{ inputs.repo_branch }}"
          echo "The vers ${{ inputs.vers }}"
          if [[ "${{ inputs.repo_branch }}" == "main" ]]; then
            env="PROD"
          else
            env=$(echo "${{ inputs.repo_branch }}" | tr '[:lower:]' '[:upper:]')
          fi
          echo "The env ${env}"

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: docs
          path: ${{ inputs.repo_name }}

      - name: edit vers svg
        shell: bash
        run: |
          set -eu
          cd ${{ inputs.repo_name }}/docs
          # Replace the VER-xxx.xxx with the input version
          sed -i '' "s/\(<h3>"${env}"<\/h3>.*VER-\)[0-9]\+\.[0-9]\+\(-blue?style=for-the-badge<\/img>\)/\1${{ inputs.vers }}\2/" index.html

      # - name: edit status svg
      #   shell: bash
      #   run: |
      #     set -eu
      #     cd "${{ inputs.repo_name }}"

      #     if [ "${{ inputs.job_status }}" = "success" ]; then
      #         sed 's/"#c7b7b7"/"green"/g; s/{{STATUS}}/pass/g' assets/blank_status.svg > updated_status.svg
      #     elif [ "${{ inputs.job_status }}" = "failure" ]; then
      #         sed 's/"#c7b7b7"/"red"/g; s/{{STATUS}}/fail/g' assets/blank_status.svg > updated_status.svg
      #     else
      #         echo "Invalid job status. Cannot update status badge."
      #         exit 1
      #     fi

      #     mv updated_status.svg assets/"${{ inputs.env_name }}"_build_status.svg

      - name: Configure git and push commit
        run: |
          set -eu
          cd ${{ inputs.repo_name }}
          git config user.name "mm808"
          git config user.email "mm808@users.noreply.github.com"
          git add .
          git commit -m "Automated badge update by update_readme_badges GitHub workflow"
          git push
