name: Edit badges

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        required: true
      repo_branch:
        type: string
        required: true
      env_name:
        type: string
        required: true
      vers:
        type: string
        required: true

permissions:
  contents: write

jobs:
  Edit_Badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ inputs.repo_name }}

      - name: debug inputs
        run: |
          echo "The repo ${{ inputs.repo_name }}"
          echo "The branch ${{ inputs.repo_branch }}"
          echo "The vers ${{ inputs.vers }}"
          echo "The env_name ${{ inputs.env_name }}"

      - name: edit vers svg
        shell: bash
        run: |
          set -eu
          cd ${{ inputs.repo_name }}
          # Replace the {{VERSION}} placeholder in template.svg with the input version
          sed "s/{{VERSION}}/${{ inputs.vers }}/g" assets/${{ inputs.env_name }}_vers.svg > updated.svg
          mv updated.svg assets/${{ inputs.env_name }}_vers.svg
          
          cat assets/${{ inputs.env_name}}_vers.svg

      - name: Configure git and push commit
        run: |
          set -eu
          cd ${{ inputs.repo_name }}
          git config user.name "mm808"
          git config user.email "mm808@users.noreply.github.com"
          git add .
          git commit -m "Automated badge update by update_readme_badges GitHub workflow"
          git push